import React, { Fragment } from "react";
export default function Colors() {
  return (
    <Fragment>
      <defs id="SvgjsDefs1001">
        <radialGradient
          id="SvgjsRadialGradient2886"
          cx="100"
          cy="114"
          r="41"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-facehighlight-gradient-single-0"
        >
          <stop
            id="SvgjsStop2887"
            stop-opacity="0.5"
            stop-color="#ffe4d6"
            offset="0"
            data-stoptype="hl1"
          ></stop>
          <stop
            id="SvgjsStop2888"
            stop-opacity="0"
            stop-color="#f0c7b1"
            offset="0.9"
            data-stoptype="tone"
          ></stop>
        </radialGradient>
        <radialGradient
          id="SvgjsRadialGradient2890"
          cx="100"
          cy="54"
          r="37"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-facehighlight-gradient-single-1"
        >
          <stop
            id="SvgjsStop2891"
            stop-opacity="0.5"
            stop-color="#ffe4d6"
            offset="0"
            data-stoptype="hl1"
          ></stop>
          <stop
            id="SvgjsStop2892"
            stop-opacity="0"
            stop-color="#f0c7b1"
            offset="0.9"
            data-stoptype="tone"
          ></stop>
        </radialGradient>
        <radialGradient
          id="SvgjsRadialGradient3478"
          cx="-568.659"
          cy="-521.042"
          r="59.751"
          gradientTransform="matrix(0.096 -0.0248 0.0245 0.0961 141.2814 119.9893)"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-eyesiris-gradient-left-1"
        >
          <stop
            id="SvgjsStop3479"
            stop-opacity="1"
            stop-color="#ffffff"
            offset="0"
            data-stoptype="#ffffff"
          ></stop>
          <stop
            id="SvgjsStop3480"
            stop-opacity="0"
            stop-color="#ffffff"
            offset="1"
            data-stoptype="#ffffff"
          ></stop>
        </radialGradient>
        <radialGradient
          id="SvgjsRadialGradient3482"
          cx="-582.838"
          cy="-519.099"
          r="59.745"
          gradientTransform="matrix(0.0991 8.856319e-004 -0.0011 0.0991 131.1134 135.9855)"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-eyesiris-gradient-left-2"
        >
          <stop
            id="SvgjsStop3483"
            stop-opacity="1"
            stop-color="#ffffff"
            offset="0"
            data-stoptype="#ffffff"
          ></stop>
          <stop
            id="SvgjsStop3484"
            stop-opacity="0"
            stop-color="#ffffff"
            offset="1"
            data-stoptype="#ffffff"
          ></stop>
        </radialGradient>
        <linearGradient
          id="SvgjsLinearGradient3488"
          x1="122.67"
          y1="88.268"
          x2="123.606"
          y2="87.152"
          gradientTransform="matrix(1 0 0 1 -52 0)"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-eyesiris-gradient-left-5"
        >
          <stop
            id="SvgjsStop3489"
            stop-opacity="1"
            stop-color="#ffffff"
            offset="0"
            data-stoptype="#ffffff"
          ></stop>
          <stop
            id="SvgjsStop3490"
            stop-opacity="0"
            stop-color="#ffffff"
            offset="1"
            data-stoptype="#ffffff"
          ></stop>
        </linearGradient>
        <linearGradient
          id="SvgjsLinearGradient3492"
          x1="127.212"
          y1="82.296"
          x2="126.463"
          y2="83.189"
          gradientTransform="matrix(1 0 0 1 -52 0)"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-eyesiris-gradient-left-6"
        >
          <stop
            id="SvgjsStop3493"
            stop-opacity="1"
            stop-color="#ffffff"
            offset="0"
            data-stoptype="#ffffff"
          ></stop>
          <stop
            id="SvgjsStop3494"
            stop-opacity="0"
            stop-color="#ffffff"
            offset="1"
            data-stoptype="#ffffff"
          ></stop>
        </linearGradient>
        <linearGradient
          id="SvgjsLinearGradient3496"
          x1="129.636"
          y1="79.822"
          x2="127.91"
          y2="81.879"
          gradientTransform="matrix(1 0 0 1 -52 0)"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-eyesiris-gradient-left-7"
        >
          <stop
            id="SvgjsStop3497"
            stop-opacity="1"
            stop-color="#ffffff"
            offset="0"
            data-stoptype="#ffffff"
          ></stop>
          <stop
            id="SvgjsStop3498"
            stop-opacity="0"
            stop-color="#ffffff"
            offset="1"
            data-stoptype="#ffffff"
          ></stop>
        </linearGradient>
        <radialGradient
          id="SvgjsRadialGradient3501"
          cx="-568.654"
          cy="-521.042"
          r="59.752"
          gradientTransform="matrix(0.096 -0.0248 0.0245 0.0961 193.2804 119.9894)"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-eyesiris-gradient-right-1"
        >
          <stop
            id="SvgjsStop3502"
            stop-opacity="1"
            stop-color="#ffffff"
            offset="0"
            data-stoptype="#ffffff"
          ></stop>
          <stop
            id="SvgjsStop3503"
            stop-opacity="0"
            stop-color="#ffffff"
            offset="1"
            data-stoptype="#ffffff"
          ></stop>
        </radialGradient>
        <radialGradient
          id="SvgjsRadialGradient3505"
          cx="-582.833"
          cy="-519.102"
          r="59.747"
          gradientTransform="matrix(0.0991 8.856319e-004 -0.0011 0.0991 183.1126 135.9856)"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-eyesiris-gradient-right-2"
        >
          <stop
            id="SvgjsStop3506"
            stop-opacity="1"
            stop-color="#ffffff"
            offset="0"
            data-stoptype="#ffffff"
          ></stop>
          <stop
            id="SvgjsStop3507"
            stop-opacity="0"
            stop-color="#ffffff"
            offset="1"
            data-stoptype="#ffffff"
          ></stop>
        </radialGradient>
        <linearGradient
          id="SvgjsLinearGradient3511"
          x1="122.67"
          y1="88.268"
          x2="123.606"
          y2="87.152"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-eyesiris-gradient-right-5"
        >
          <stop
            id="SvgjsStop3512"
            stop-opacity="1"
            stop-color="#ffffff"
            offset="0"
            data-stoptype="#ffffff"
          ></stop>
          <stop
            id="SvgjsStop3513"
            stop-opacity="0"
            stop-color="#ffffff"
            offset="1"
            data-stoptype="#ffffff"
          ></stop>
        </linearGradient>
        <linearGradient
          id="SvgjsLinearGradient3515"
          x1="127.212"
          y1="82.296"
          x2="126.463"
          y2="83.189"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-eyesiris-gradient-right-6"
        >
          <stop
            id="SvgjsStop3516"
            stop-opacity="1"
            stop-color="#ffffff"
            offset="0"
            data-stoptype="#ffffff"
          ></stop>
          <stop
            id="SvgjsStop3517"
            stop-opacity="0"
            stop-color="#ffffff"
            offset="1"
            data-stoptype="#ffffff"
          ></stop>
        </linearGradient>
        <linearGradient
          id="SvgjsLinearGradient3519"
          x1="129.636"
          y1="79.822"
          x2="127.91"
          y2="81.879"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-eyesiris-gradient-right-7"
        >
          <stop
            id="SvgjsStop3520"
            stop-opacity="1"
            stop-color="#ffffff"
            offset="0"
            data-stoptype="#ffffff"
          ></stop>
          <stop
            id="SvgjsStop3521"
            stop-opacity="0"
            stop-color="#ffffff"
            offset="1"
            data-stoptype="#ffffff"
          ></stop>
        </linearGradient>
        <linearGradient
          id="SvgjsLinearGradient3565"
          x1="130"
          y1="69"
          x2="130"
          y2="109"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-glasses-gradient-single-0"
        >
          <stop
            id="SvgjsStop3566"
            stop-opacity="1"
            stop-color="#000000"
            offset="0"
            data-stoptype="#000000"
          ></stop>
          <stop
            id="SvgjsStop3567"
            stop-opacity="0.8"
            stop-color="#000000"
            offset="1"
            data-stoptype="#000000"
          ></stop>
        </linearGradient>
        <linearGradient
          id="SvgjsLinearGradient3569"
          x1="130"
          y1="69"
          x2="130"
          y2="109"
          gradientTransform="matrix(-1 0 0 1 200 0)"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-glasses-gradient-single-1"
        >
          <stop
            id="SvgjsStop3570"
            stop-opacity="1"
            stop-color="#000000"
            offset="0"
            data-stoptype="#000000"
          ></stop>
          <stop
            id="SvgjsStop3571"
            stop-opacity="0.8"
            stop-color="#000000"
            offset="1"
            data-stoptype="#000000"
          ></stop>
        </linearGradient>
        <radialGradient
          id="SvgjsRadialGradient3630"
          cx="127.199"
          cy="84.835"
          r="14"
          gradientTransform="matrix(-1 0 0 1 200 0)"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-eyesback-gradient-left-0"
        >
          <stop
            id="SvgjsStop3631"
            stop-opacity="1"
            stop-color="#ffffff"
            offset="0"
            data-stoptype="#ffffff"
          ></stop>
          <stop
            id="SvgjsStop3632"
            stop-opacity="1"
            stop-color="#fdfefe"
            offset="0.544"
            data-stoptype="#fdfefe"
          ></stop>
          <stop
            id="SvgjsStop3633"
            stop-opacity="1"
            stop-color="#f6f8f9"
            offset="0.74"
            data-stoptype="#f6f8f9"
          ></stop>
          <stop
            id="SvgjsStop3634"
            stop-opacity="1"
            stop-color="#eaeff2"
            offset="0.879"
            data-stoptype="#eaeff2"
          ></stop>
          <stop
            id="SvgjsStop3635"
            stop-opacity="1"
            stop-color="#d9e3e8"
            offset="0.992"
            data-stoptype="#d9e3e8"
          ></stop>
          <stop
            id="SvgjsStop3636"
            stop-opacity="1"
            stop-color="#d8e2e7"
            offset="1"
            data-stoptype="#d8e2e7"
          ></stop>
        </radialGradient>
        <radialGradient
          id="SvgjsRadialGradient3638"
          cx="126.801"
          cy="84.835"
          r="14"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-eyesback-gradient-right-0"
        >
          <stop
            id="SvgjsStop3639"
            stop-opacity="1"
            stop-color="#ffffff"
            offset="0"
            data-stoptype="#ffffff"
          ></stop>
          <stop
            id="SvgjsStop3640"
            stop-opacity="1"
            stop-color="#fdfefe"
            offset="0.544"
            data-stoptype="#fdfefe"
          ></stop>
          <stop
            id="SvgjsStop3641"
            stop-opacity="1"
            stop-color="#f6f8f9"
            offset="0.74"
            data-stoptype="#f6f8f9"
          ></stop>
          <stop
            id="SvgjsStop3642"
            stop-opacity="1"
            stop-color="#eaeff2"
            offset="0.879"
            data-stoptype="#eaeff2"
          ></stop>
          <stop
            id="SvgjsStop3643"
            stop-opacity="1"
            stop-color="#d9e3e8"
            offset="0.992"
            data-stoptype="#d9e3e8"
          ></stop>
          <stop
            id="SvgjsStop3644"
            stop-opacity="1"
            stop-color="#d8e2e7"
            offset="1"
            data-stoptype="#d8e2e7"
          ></stop>
        </radialGradient>
        <radialGradient
          id="SvgjsRadialGradient3646"
          cx="127.199"
          cy="84.835"
          r="14"
          gradientTransform="matrix(-1 0 0 1 200 0)"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-eyesfront-gradient-left-0"
        >
          <stop
            id="SvgjsStop3647"
            stop-opacity="1"
            stop-color="#ffffff"
            offset="0"
            data-stoptype="#ffffff"
          ></stop>
          <stop
            id="SvgjsStop3648"
            stop-opacity="1"
            stop-color="#fdfefe"
            offset="0.544"
            data-stoptype="#fdfefe"
          ></stop>
          <stop
            id="SvgjsStop3649"
            stop-opacity="1"
            stop-color="#f6f8f9"
            offset="0.74"
            data-stoptype="#f6f8f9"
          ></stop>
          <stop
            id="SvgjsStop3650"
            stop-opacity="1"
            stop-color="#eaeff2"
            offset="0.879"
            data-stoptype="#eaeff2"
          ></stop>
          <stop
            id="SvgjsStop3651"
            stop-opacity="1"
            stop-color="#d9e3e8"
            offset="0.992"
            data-stoptype="#d9e3e8"
          ></stop>
          <stop
            id="SvgjsStop3652"
            stop-opacity="1"
            stop-color="#d8e2e7"
            offset="1"
            data-stoptype="#d8e2e7"
          ></stop>
        </radialGradient>
        <radialGradient
          id="SvgjsRadialGradient3656"
          cx="125.36"
          cy="83.943"
          fx="138.934"
          fy="82.45"
          r="18.705"
          gradientTransform="matrix(0.9998 0.0208 0.0131 -0.6281 -51.791 134.0611)"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-eyesfront-gradient-left-3"
        >
          <stop
            id="SvgjsStop3657"
            stop-opacity="1"
            stop-color="#e1ac8f"
            offset="0"
            data-stoptype="sd1"
          ></stop>
          <stop
            id="SvgjsStop3658"
            stop-opacity="0.3"
            stop-color="#e1ac8f"
            offset="0.7"
            data-stoptype="sd1"
          ></stop>
          <stop
            id="SvgjsStop3659"
            stop-opacity="0"
            stop-color="#f0c7b1"
            offset="1"
            data-stoptype="tone"
          ></stop>
        </radialGradient>
        <radialGradient
          id="SvgjsRadialGradient3661"
          cx="67.679"
          cy="106.859"
          r="29.505"
          gradientTransform="matrix(1.0322 -0.0541 0.0541 1.0322 -5.894 5.3941)"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-eyesfront-gradient-left-4"
        >
          <stop
            id="SvgjsStop3662"
            stop-opacity="0"
            stop-color="#000000"
            offset="0.95"
            data-stoptype="#000000"
          ></stop>
          <stop
            id="SvgjsStop3663"
            stop-opacity="0.2"
            stop-color="#000000"
            offset="1"
            data-stoptype="#000000"
          ></stop>
        </radialGradient>
        <radialGradient
          id="SvgjsRadialGradient3667"
          cx="126.801"
          cy="84.835"
          r="14"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-eyesfront-gradient-right-0"
        >
          <stop
            id="SvgjsStop3668"
            stop-opacity="1"
            stop-color="#ffffff"
            offset="0"
            data-stoptype="#ffffff"
          ></stop>
          <stop
            id="SvgjsStop3669"
            stop-opacity="1"
            stop-color="#fdfefe"
            offset="0.544"
            data-stoptype="#fdfefe"
          ></stop>
          <stop
            id="SvgjsStop3670"
            stop-opacity="1"
            stop-color="#f6f8f9"
            offset="0.74"
            data-stoptype="#f6f8f9"
          ></stop>
          <stop
            id="SvgjsStop3671"
            stop-opacity="1"
            stop-color="#eaeff2"
            offset="0.879"
            data-stoptype="#eaeff2"
          ></stop>
          <stop
            id="SvgjsStop3672"
            stop-opacity="1"
            stop-color="#d9e3e8"
            offset="0.992"
            data-stoptype="#d9e3e8"
          ></stop>
          <stop
            id="SvgjsStop3673"
            stop-opacity="1"
            stop-color="#d8e2e7"
            offset="1"
            data-stoptype="#d8e2e7"
          ></stop>
        </radialGradient>
        <radialGradient
          id="SvgjsRadialGradient3677"
          cx="124.961"
          cy="83.943"
          fx="138.535"
          fy="82.45"
          r="18.705"
          gradientTransform="matrix(-0.9998 0.0208 -0.0131 -0.6281 250.9922 134.0695)"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-eyesfront-gradient-right-3"
        >
          <stop
            id="SvgjsStop3678"
            stop-opacity="1"
            stop-color="#e1ac8f"
            offset="0"
            data-stoptype="sd1"
          ></stop>
          <stop
            id="SvgjsStop3679"
            stop-opacity="0.3"
            stop-color="#e1ac8f"
            offset="0.7"
            data-stoptype="sd1"
          ></stop>
          <stop
            id="SvgjsStop3680"
            stop-opacity="0"
            stop-color="#f0c7b1"
            offset="1"
            data-stoptype="tone"
          ></stop>
        </radialGradient>
        <radialGradient
          id="SvgjsRadialGradient3682"
          cx="68.065"
          cy="106.876"
          r="29.506"
          gradientTransform="matrix(-1.0322 -0.0541 -0.0541 1.0322 205.8938 5.3986)"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-eyesfront-gradient-right-4"
        >
          <stop
            id="SvgjsStop3683"
            stop-opacity="0"
            stop-color="#000000"
            offset="0.95"
            data-stoptype="#000000"
          ></stop>
          <stop
            id="SvgjsStop3684"
            stop-opacity="0.2"
            stop-color="#000000"
            offset="1"
            data-stoptype="#000000"
          ></stop>
        </radialGradient>
        <linearGradient
          id="SvgjsLinearGradient3695"
          x1="100"
          y1="172"
          x2="100"
          y2="123"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-chinshadow-gradient-single-0"
        >
          <stop
            id="SvgjsStop3696"
            stop-opacity="0.8"
            stop-color="#e1ac8f"
            offset="0"
            data-stoptype="sd1"
          ></stop>
          <stop
            id="SvgjsStop3697"
            stop-opacity="1"
            stop-color="#c27b55"
            offset="0.7"
            data-stoptype="sd3"
          ></stop>
        </linearGradient>
        <linearGradient
          id="SvgjsLinearGradient3704"
          x1="100"
          y1="142"
          x2="100"
          y2="139"
          gradientUnits="userSpaceOnUse"
          className="svga-on-canvas-mouth-gradient-single-0"
        >
          <stop
            id="SvgjsStop3705"
            stop-opacity="1"
            stop-color="#e8b9a0"
            offset="0.1"
            data-stoptype="sd05"
          ></stop>
          <stop
            id="SvgjsStop3706"
            stop-opacity="1"
            stop-color="#e1ac8f"
            offset="1"
            data-stoptype="sd1"
          ></stop>
        </linearGradient>
      </defs>
    </Fragment>
  );
}
